#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Wed Nov 19 04:03:02 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana3.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame_2")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.spin_ctrl_1 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_3.Add(self.spin_ctrl_1, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico$75")
        grid_sizer_4.Add(label_2, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_4.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_7 = wx.GridSizer(2, 1, 0, 0)
        sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch")
        grid_sizer_7.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco ch")
        grid_sizer_7.Add(label_4, 0, 0, 0)

        grid_sizer_3.Add((0, 0), 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.spin_ctrl_2 = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_5.Add(self.spin_ctrl_2, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "bbf")
        grid_sizer_6.Add(label_5, 0, 0, 0)

        grid_sizer_6.Add((0, 0), 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        sizer_1.Add((0, 0), 0, 0, 0)

        sizer_1.Add((0, 0), 0, 0, 0)

        sizer_1.Add((0, 0), 0, 0, 0)

        sizer_1.Add((0, 0), 0, 0, 0)

        sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class Ventana3

class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((598, 733))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((100, 120))
        self.panel_1.SetBackgroundColour(wx.Colour(95, 121, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(2, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./SeleEstre/Nueva carpeta/imagenes22/logo rosi.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((145, 80))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetMinSize((50, 40))
        label_1.SetBackgroundColour(wx.Colour(84, 142, 255))
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Subheading"))
        grid_sizer_1.Add(label_1, 0, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./SeleEstre/Nueva carpeta/imagenes22/logo rosi.jpg", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((140, 60))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        label_2.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Subheading"))
        sizer_2.Add(label_2, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_7.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Times New Roman"))
        sizer_2.Add(label_7, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:", style=wx.ALIGN_CENTER_HORIZONTAL | wx.ST_ELLIPSIZE_START | wx.ST_NO_AUTORESIZE)
        label_11.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Sitka Display"))
        sizer_2.Add(label_11, 0, 0, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["El cadaver de la novia", "Spiderman", "El conjuro"], style=wx.CB_DROPDOWN)
        sizer_3.Add(self.cmbPelicula, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbSala.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_3.Add(self.lbSala, 0, 0, 0)

        grid_sizer_14 = wx.GridSizer(2, 2, 0, 0)
        sizer_3.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        grid_sizer_15 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_14.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.rbhorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_15.Add(self.rbhorario1, 0, 0, 0)

        grid_sizer_16 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_14.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        self.rbhorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_16.Add(self.rbhorario2, 0, 0, 0)

        grid_sizer_17 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_14.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        self.rbhorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_17.Add(self.rbhorario3, 0, 0, 0)

        grid_sizer_18 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_14.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        grid_sizer_18.Add((0, 0), 0, 0, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./SeleEstre/Nueva carpeta/imagenes22/images.jpg", wx.BITMAP_TYPE_ANY), style=wx.BORDER_SIMPLE)
        grid_sizer_1.Add(self.bmPelicula, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_11 = wx.GridSizer(0, 1, 0, 0)
        sizer_1.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "boletos")
        label_3.SetMinSize((85, 26))
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_11.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_19 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_11.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "ADULTOS($100)")
        grid_sizer_19.Add(label_15, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_19.Add(self.tfAdultos, 0, 0, 0)

        grid_sizer_20 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_11.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores ($65)")
        grid_sizer_20.Add(label_16, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_20.Add(self.tfMenores, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal $")
        label_4.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_11.Add(label_4, 0, 0, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_11.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n")
        self.btnLimpiar.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "SimSun"))
        grid_sizer_2.Add(self.btnLimpiar, 0, 0, 0)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        self.button_2.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "SimSun"))
        grid_sizer_2.Add(self.button_2, 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbhorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbhorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbhorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.LimpiarTaquilla)
        self.button_2.Bind(wx.EVT_BUTTON, self.SiguienteVentana)
        # end wxGlade

    def cargar_imagen(self, ruta_imagen):
        bitmap = wx.Bitmap(ruta_imagen, wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula= self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""
        print(f"pelicula seleccionada: {pelicula}")
        if pelicula=="El cadaver de la novia":
            imagen="images.jpg"
            sala="sala 1"
            horario1="12:00"
            horario2="15:00"
            horario3="18:00"
        elif pelicula=="Spiderman":
            imagen="images (1) spiderman.jpg"
            sala="sala 2"
            horario1="13:00"
            horario2="16:00"
            horario3="19:00"
        elif pelicula=="El conjuro":
            imagen="the-conjuring-poster.jpg"
            sala="sala 3"
            horario1="14:00"
            horario2="17:00"
            horario3="20:00"

        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbhorario1.SetLabel(horario1)
        self.rbhorario2.SetLabel(horario2)
        self.rbhorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'seleccionHorario1' not implemented!")
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'seleccionHorario2' not implemented!")
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'seleccionHorario3' not implemented!")
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'sumarAdultos' not implemented!")
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'sumarMenores' not implemented!")
        event.Skip()

    def LimpiarTaquilla(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'LimpiarTaquilla' not implemented!")
        event.Skip()

    def SiguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        print("Event handler 'SiguienteVentana' not implemented!")
        event.Skip()

# end of class Ventana2

class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((612, 426))
        self.SetTitle(u"inicio de sesi�n - Cine Plus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("E:\\descarga.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(189, 189, 97))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenidos a cineplus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetForegroundColour(wx.Colour(219, 112, 147))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        ibLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./descarga.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(ibLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbtitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbtitulo.SetMinSize((445, 35))
        lbtitulo.SetForegroundColour(wx.Colour(219, 112, 147))
        lbtitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbtitulo, 0, wx.EXPAND, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contrase�a", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((445, 30))
        lbClave.SetForegroundColour(wx.Colour(219, 112, 147))
        lbClave.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbClave, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        sizer_1.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.button_1.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.button_2.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()

        if nombre == "selestre" and clave == "123":
            print(f"¡bienvenida, {nombre}! acceso autorizado.")
            v2= Ventana2(self)
            v2.Show()
            self.Hide()
        else:
            print("Acesso denegado usuario o clave incorrectos")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
       
        pregunta = wx.MessageDialog(self, "se cerrara la ventana.\n" \
        "¿estas seguro que quieres salir?","confirma salida",style=wx.YES_NO | wx.ICON_QUESTION)
        respuesta = pregunta.ShowModal()
        pregunta.Destroy() # Cerramos el codigo 

        if respuesta == wx.ID_YES:
            print("bye!")
        self.Close() # cierrra la ventana

        event.Skip()
# end of class Ventana1

class MyAppcineplus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppcineplus

if __name__ == "__main__":
    appcineplus = MyAppcineplus(0)
    appcineplus.MainLoop()
